# fly.toml app configuration file generated for brosef on 2023-05-04T12:35:20+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brosef"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "syd"
processes = []

[build]

[env]
  PORT = 8080

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.script_checks]]
    command = "/myapp/health_check.sh"
    grace_period = "1s"
    interval = "5s"
    restart_limit = 0
    timeout = "1s"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
